version: '3.8'

services:
  db:
    build: .
    container_name: 'gym-pass-container'
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=`${POSTGRESQL_DATABASE}-docker`

volumes:
  postgres:
    driver: local