version: '3.8'

services:
  db:
    build: .
    container_name: 'CONTAINER_NAME-container'
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=CONTAINER_NAME-docker

volumes:
  postgres:
    driver: local